# Generated by Django 5.2 on 2025-04-11 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_urlfield_alter_project_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='URLField',
            new_name='link',
        ),
    ]
